const os=require("os")
console.log(os.userInfo())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.totalmem())
console.log(os.freemem())
console.log(os._dirname())
console.log(os._filename())